# Generated by Django 5.0.3 on 2024-07-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_input", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="name",
            new_name="data",
        ),
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
    ]
